services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
